import { QuizItem } from "./QuizCategory";
import { TbBriefcase, TbDeviceDesktop, TbEmpathize } from "react-icons/tb";
import {
    TbBrandJavascript,
    TbBrandTypescript,
    TbBrandHtml5,
    TbBrandCss3,
    TbBrandSass,
    TbBrandReact,
    TbBrandVue,
    TbBrandAngular,
    TbBrandNextjs,
    TbBrandNodejs,
    TbBrandDocker,
    TbCloudComputing,
    TbShieldLock,
    TbBrain,
    TbBrandFlutter,
    TbDeviceMobileCode,
} from "react-icons/tb";

export const quizCategories: QuizItem[] = [
    {
        id: "technical-it",
        title: "Technical IT",
        description: "Test your technical knowledge in programming, networking, cybersecurity, and more",
        icon: <TbDeviceDesktop className="icon-sm text-blue-400" />,
        quizCount: 12,
        color: "from-blue-600/20 to-blue-400/20",
        borderColor: "hover:border-blue-400",
        route: "/quiz/technical",
    },
    {
        id: "situational",
        title: "Situational Cases",
        description: "Assess how you would handle real-world workplace scenarios and challenges",
        icon: <TbBriefcase className="icon-sm text-purple-400" />,
        quizCount: 8,
        color: "from-purple-600/20 to-purple-400/20",
        borderColor: "hover:border-purple-400",
        route: "/quiz/case",
    },
    {
        id: "personality",
        title: "Personality & MBTI",
        description: "Discover your personality type, work preferences, and character traits",
        icon: <TbEmpathize className="icon-sm text-amber-400" />,
        quizCount: 6,
        color: "from-amber-600/20 to-amber-400/20",
        borderColor: "hover:border-amber-400",
        route: "/quiz/personality",
    },
];

export const technicalTopicItems: QuizItem[] = [
    {
        id: "javascript",
        title: "JavaScript",
        description: "Core programming for the web",
        icon: <TbBrandJavascript className="text-yellow-400" />,
        quizCount: 10,
        color: "from-yellow-500/20 to-yellow-300/20",
        borderColor: "hover:border-yellow-400",
        route: "/quiz/technical/javascript",
        group: "Frontend",
    },
    {
        id: "typescript",
        title: "TypeScript",
        description: "Strongly typed JavaScript",
        icon: <TbBrandTypescript className="text-blue-400" />,
        quizCount: 6,
        color: "from-blue-500/20 to-blue-300/20",
        borderColor: "hover:border-blue-400",
        route: "/quiz/technical/typescript",
        group: "Frontend",
    },
    {
        id: "html",
        title: "HTML",
        description: "Structure of web content",
        icon: <TbBrandHtml5 className="text-orange-400" />,
        quizCount: 5,
        color: "from-orange-500/20 to-orange-300/20",
        borderColor: "hover:border-orange-400",
        route: "/quiz/technical/html",
        group: "Frontend",
    },
    {
        id: "css",
        title: "CSS",
        description: "Styling web interfaces",
        icon: <TbBrandCss3 className="text-blue-300" />,
        quizCount: 7,
        color: "from-blue-400/20 to-blue-200/20",
        borderColor: "hover:border-blue-300",
        route: "/quiz/technical/css",
        group: "Frontend",
    },
    {
        id: "sass",
        title: "SASS",
        description: "Advanced CSS with variables",
        icon: <TbBrandSass className="text-pink-400" />,
        quizCount: 3,
        color: "from-pink-500/20 to-pink-300/20",
        borderColor: "hover:border-pink-400",
        route: "/quiz/technical/sass",
        group: "Frontend",
    },
    {
        id: "react",
        title: "React",
        description: "Modern UI library by Facebook",
        icon: <TbBrandReact className="text-cyan-400" />,
        quizCount: 9,
        color: "from-cyan-500/20 to-cyan-300/20",
        borderColor: "hover:border-cyan-400",
        route: "/quiz/technical/react",
        group: "Frontend",
    },
    {
        id: "vue",
        title: "Vue",
        description: "Progressive JavaScript framework",
        icon: <TbBrandVue className="text-green-400" />,
        quizCount: 5,
        color: "from-green-500/20 to-green-300/20",
        borderColor: "hover:border-green-400",
        route: "/quiz/technical/vue",
        group: "Frontend",
    },
    {
        id: "angular",
        title: "Angular",
        description: "Full-fledged front-end framework",
        icon: <TbBrandAngular className="text-red-400" />,
        quizCount: 4,
        color: "from-red-500/20 to-red-300/20",
        borderColor: "hover:border-red-400",
        route: "/quiz/technical/angular",
        group: "Frontend",
    },
    {
        id: "nextjs",
        title: "Next.js",
        description: "Full-stack React framework",
        icon: <TbBrandNextjs className="text-white" />,
        quizCount: 6,
        color: "from-zinc-600/20 to-zinc-400/20",
        borderColor: "hover:border-zinc-400",
        route: "/quiz/technical/nextjs",
        group: "Frontend",
    },
    {
        id: "nodejs",
        title: "Node.js",
        description: "JavaScript on the server",
        icon: <TbBrandNodejs className="text-green-500" />,
        quizCount: 8,
        color: "from-green-600/20 to-green-400/20",
        borderColor: "hover:border-green-500",
        route: "/quiz/technical/nodejs",
        group: "Backend",
    },
    {
        id: "docker",
        title: "Docker",
        description: "Containerize all the things",
        icon: <TbBrandDocker className="text-sky-400" />,
        quizCount: 5,
        color: "from-sky-600/20 to-sky-400/20",
        borderColor: "hover:border-sky-400",
        route: "/quiz/technical/docker",
        group: "DevOps",
    },
    {
        id: "cloud",
        title: "Cloud",
        description: "Computing in the cloud",
        icon: <TbCloudComputing className="text-indigo-400" />,
        quizCount: 7,
        color: "from-indigo-500/20 to-indigo-300/20",
        borderColor: "hover:border-indigo-400",
        route: "/quiz/technical/cloud",
        group: "Cloud & Infra",
    },
    {
        id: "security",
        title: "Security",
        description: "Protecting systems and data",
        icon: <TbShieldLock className="text-rose-400" />,
        quizCount: 6,
        color: "from-rose-500/20 to-rose-300/20",
        borderColor: "hover:border-rose-400",
        route: "/quiz/technical/security",
        group: "AI & Security",
    },
    {
        id: "ai",
        title: "Artificial Intelligence",
        description: "Machine intelligence topics",
        icon: <TbBrain className="text-fuchsia-400" />,
        quizCount: 5,
        color: "from-fuchsia-600/20 to-fuchsia-400/20",
        borderColor: "hover:border-fuchsia-400",
        route: "/quiz/technical/ai",
        group: "AI & Security",
    },
    {
        id: "flutter",
        title: "Flutter",
        description: "Cross-platform mobile apps",
        icon: <TbBrandFlutter className="text-sky-300" />,
        quizCount: 4,
        color: "from-sky-500/20 to-sky-300/20",
        borderColor: "hover:border-sky-300",
        route: "/quiz/technical/flutter",
        group: "Mobile",
    },
    {
        id: "react-native",
        title: "React Native",
        description: "Mobile development with React",
        icon: <TbDeviceMobileCode className="text-cyan-300" />,
        quizCount: 4,
        color: "from-cyan-500/20 to-cyan-300/20",
        borderColor: "hover:border-cyan-300",
        route: "/quiz/technical/react-native",
        group: "Mobile",
    },
];
